# Generated by Django 4.2.25 on 2025-10-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(max_length=255, verbose_name="Имя гостя"),
                ),
                (
                    "guest_email",
                    models.EmailField(max_length=254, verbose_name="Email гостя"),
                ),
                ("check_in_date", models.DateField(verbose_name="Дата заезда")),
                ("check_out_date", models.DateField(verbose_name="Дата выезда")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Общая стоимость"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="rooms.hotelroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "db_table": "bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
