# Generated by Django 4.2.25 on 2025-10-29 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["check_in_date"],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_email",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="rooms.hotelroom",
                verbose_name="Номер отеля",
            ),
        ),
    ]
