# Generated by Django 4.2.25 on 2025-10-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_options_remove_booking_guest_email_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("room", "check_in_date", "check_out_date"),
                name="unique_booking_per_room_dates",
            ),
        ),
    ]
